name: ${name}
description: ${description}
authors: ['fran2019', 'ale28crack']
main: ${mainClass}
version: ${version}
url: https://github.com/ImperiorDevelopment/Freerank
commands:
  freerank:
    description: "This is a freerank command"