
███████╗██████╗░███████╗███████╗██████╗░░█████╗░███╗░░██╗██╗░░██╗
██╔════╝██╔══██╗██╔════╝██╔════╝██╔══██╗██╔══██╗████╗░██║██║░██╔╝
█████╗░░██████╔╝█████╗░░█████╗░░██████╔╝███████║██╔██╗██║█████═╝░
██╔══╝░░██╔══██╗██╔══╝░░██╔══╝░░██╔══██╗██╔══██║██║╚████║██╔═██╗░
██║░░░░░██║░░██║███████╗███████╗██║░░██║██║░░██║██║░╚███║██║░╚██╗
╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝
# Configuración de Freerank
freerank:
# Rango que se otorgará a los jugadores
  rank: "default" 
 # Mensaje que se mostrará al jugador después de que se le otorgue el rango
  message: "&a¡Felicidades! Ahora eres miembro del servidor"
