name: Freerank
description: This is just a freerank plugin
authors: ['fran2019', 'ale28crack']
main: dev.fran2019.imperiordevelopment.FreeRank
version: 1.3
url: https://github.com/ImperiorDevelopment/Freerank
commands:
  freerank:
    description: "This is a freerank command"